spring.application.name=Vestaboard

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

app.gateway.vestaboard.base-url=https://cloud.vestaboard.com/
app.gateway.vestaboard.token=98006aa0921f41a5b84c960f12b3b098
app.gateway.vestaboard.vbml.base-url=https://vbml.vestaboard.com/compose